### ISSUE TITLE
Error while destroying map

### ISSUE THREAD

**Issue by medokin** [Matt-Jensen/ember-cli-g-maps#1]
g-maps.js:85 Uncaught TypeError: Cannot read property 'length' of undefined

`events` is  undefined

**Comment by Matt-Jensen** [comment]
Thank you for reporting this @medokin.  Should be fixed via aeedde2ae57416b80a085fe85ed23495175ae659.  I've merged a hotfix into master and republish on npm. I'm rolling out new features soon, stay tuned!
