### ISSUE TITLE
How can i show my location like google.com/maps 's blue dot

### ISSUE THREAD

**Issue by Zorig** [Matt-Jensen/ember-cli-g-maps#100]
First of all thanks for this useful addon, now the problem is how can i show my current location ?

**Comment by Matt-Jensen** [comment]
I would use an addon to request the user's location: https://github.com/igorpreston/ember-cli-geo
Then I would render that lat/lng with a customized marker icon: http://matt-jensen.github.io/ember-cli-g-maps/#/basic-usage/markers
