### ISSUE TITLE
how to compare current latitude/longitude to previous latitude/longitude

### ISSUE THREAD

**Issue by Zorig** [Matt-Jensen/ember-cli-g-maps#101]
Hey, i want to compare current latitude and longitude then when user drag or center changed i want to calculate new longitude and latitude to previous longitude and latitude. I did try getting `this.get('lat')` so i perceived this get's only current latitude right? so how can i achieve it?

**Comment by Matt-Jensen** [comment]
This is a userland state management concern.  Issues are for bug reports and feature requests.
