### ISSUE TITLE
Markers not showing up on deployed production mode

### ISSUE THREAD

**Issue by Zorig** [Matt-Jensen/ember-cli-g-maps#102]
Hi, i have used `ember-cli-g-maps` on `ember@2.15.1`. as a local project on development it shows markers but production. There is no error report or warning, map is loaded, data fetched successfully only markers are not showing.

**Comment by Matt-Jensen** [comment]
Example repo or twiddle code please

**Comment by Zorig** [comment]
@Matt-Jensen https://ember-twiddle.com/242b86be8cc2d74bb31a08019aec610e

**Comment by Zorig** [comment]
@Matt-Jensen  also is it possible to apply https://mapstyle.withgoogle.com/ styling???

**Comment by Zorig** [comment]
I will put styling as a independent issue, @Matt-Jensen this issue if fixed, it was my bad i didn't exclude custom markers from fingerprint
