### ISSUE TITLE
FR: GroundOverlays

### ISSUE THREAD

**Issue by nsharrok** [Matt-Jensen/ember-cli-g-maps#106]
* Operating System version:  Windows 10
  * Ember CLI version:  13
  * Ember CLI G Maps version: latest
  
Hi,
I have floor plans for all the hospitals in the region and I want to create GroundOverlays so I can locate and move IT assets (computers, printers...) as custom markers across the sites.
I have created GorundOverlays using the Google Maps API and now I want to port the system to an Ember app.

I just thought that GroundOverlays would complement the other elements in your excellent ember-cli-g-maps add-on.

**Comment by Matt-Jensen** [comment]
Thanks for this feature request, for your use case I'd recommend extending this addon with the features you need.  I'm not personally going to be adding more features at this time.  Good luck with your project!
