### ISSUE TITLE
Zoom resets to initial value

### ISSUE THREAD

**Issue by maxymczech** [Matt-Jensen/ember-cli-g-maps#110]
I have this in my hbs template:
`      {{g-maps
        map=map
        lat=model.lat
        lng=model.lng
        markers=markers
        draggable=true
        showMapTypeControl=true
        showScaleControl=false
        disableDefaultUI=false
        clickableIcons=false
        fullscreenControl=false
        scrollwheel=false
      }}
`

This works great but of course it shows me all the continents etc. But if I add zoom attribute like zoom=14, I am then unable to resize the map via user interaction, it keeps returning zoom to initial value of 14.

**Comment by Matt-Jensen** [comment]
Since this is now a deprecated project it is strongly encouraged that you use [ember-google-maps](https://github.com/sandydoo/ember-google-maps) if your able to make that transition.

**Comment by maxymczech** [comment]
Ok, so the problem was that I had

```
{{g-maps zoom=14}}
```

and what I needed was a binding to some property:

```
{{g-maps zoom=mapZoom}}
```
