### ISSUE TITLE
Addon is wrecking tests

### ISSUE THREAD

**Issue by jackmatt2** [Matt-Jensen/ember-cli-g-maps#28]
The addon is working fine but it seems to be wrecking my acceptance tests.

```javascript
not ok 43 PhantomJS 1.9 - TestLoader Failures: myproject/tests/acceptance/booking/edit/account-test: could not be loaded
    ---
        actual: >
            null
        message: >
            Died on test #1     at http://localhost:7357/assets/test-support.js:2934
                at http://localhost:7357/assets/test-support.js:6640
                at http://localhost:7357/assets/test-loader.js:31
                at http://localhost:7357/assets/test-loader.js:21
                at http://localhost:7357/assets/test-loader.js:40
                at http://localhost:7357/assets/test-support.js:6647: Could not find module `ember-cli-app-version/initializer-factory` imported from `myproject/initializers/app-version`
        Log: |
```

If I remove `"ember-cli-g-maps": "0.3.2"` from my code the tests start working again.

**Comment by jackmatt2** [comment]
@Matt-Jensen it happens when I run `ember-test`. I have no idea why removing ember-cli-g-maps fixes the issue but it does.

**Comment by jackmatt2** [comment]
So are you suggesting that I might need to update to ember-data.model-fragments@v0.4.0? I looked in both the `ember-cli` and `ember-data` `package.json` but cound not find it.

**Comment by jackmatt2** [comment]
ah, sorry I am way off.  I am not using `ember-data-model-fragments`.  Still a little unsure what the resolution is.

**Comment by Matt-Jensen** [comment]
I'm not able to reproduce this on a fresh Ember-cli install w/ initializer test generated. Used `ember test` and didn't have any conflicts.

If you can ensure that `ember-cli-app-version/initializer-factory` is importing correctly and some steps to reproduce, I can help debug this further.

**Comment by jackmatt2** [comment]
OK, will try to reproduce in a demo of some sort.
