### ISSUE TITLE
Search box possible?

### ISSUE THREAD

**Issue by stijn26** [Matt-Jensen/ember-cli-g-maps#44]
Hi,

Is a search box possible in this addon?
https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

If not, how would I implement this myself (maybe even in the addon)?

**Comment by Matt-Jensen** [comment]
While no one is currently working on search box specifically, would #30 be helpful to you?  Otherwise I would welcome any PR that took the approach used by the `g-autocomplete` component currently in the 0.4 branch.

**Comment by stijn26** [comment]
Hi,
I will wait on the 0.4 release as I do not have experience with developing addons and certainly not with service unit tests in EmberJS;

**Comment by Matt-Jensen** [comment]
Sounds good. Out of curiosity, do you think #30 Places Autocomplete would foot the bill for your app?

**Comment by stijn26** [comment]
It sounds like the perfect thing, I now manually made an input that does a request to the autocomplete API from Google, I think its just the same thing.

**Comment by Matt-Jensen** [comment]
A places autocomplete component was added into the 0.4 release.
