### ISSUE TITLE
Lazy Load

### ISSUE THREAD

**Issue by estshy** [Matt-Jensen/ember-cli-g-maps#47]
I don't want to fetch google maps before it is needed. I can see in the source code that there is lazyLoad configuration options but the code is commented out. What's the status of lazy load functionality? Is this already working or if not then how can I help you in progressing with that?

**Comment by vsymguysung** [comment]
+1

**Comment by Matt-Jensen** [comment]
Shipped in v0.5.0.  Please ensure your bower dependencies are up to date as well.
