### ISSUE TITLE
Join the forces

### ISSUE THREAD

**Issue by kirantpatil** [Matt-Jensen/ember-cli-g-maps#48]
Hi Matt,

Why not contribute on single project https://github.com/asennikov/ember-g-map, since ember-g-map is supporting ember fastboot and other industry people (yahoo developer: https://github.com/asennikov/ember-g-map/commits/master?author=mike-north) are contributing to the same code base ?

Thanks.

**Comment by Matt-Jensen** [comment]
Thanks for the question. Asennikov and I have actually talked about it.

We agree there is too much fragmentation in the Ember map space. Part of the reason for that is that it is a deceptively large problem to solve.  The Google Map API surface area is huge and supporting customization with it's various features & plugins is an important problem as well.  Both `ember-g-map` and this project have a long way to go there.

When I see there's a sufficiently extensible Ember Google Map project on the horizon we can look at way's of winding down this project.

**Comment by kirantpatil** [comment]
Thanks for clarification.
