### ISSUE TITLE
gMap service to wrap gmaps-for-apps geolocate in promise

### ISSUE THREAD

**Issue by Matt-Jensen** [Matt-Jensen/ember-cli-g-maps#5]
https://developers.google.com/maps/documentation/javascript/geocoding?hl=en

Allow support for placeID if possible.

gmaps.geocode already supports reverse geocoding

**Comment by zbeat** [comment]
> gMap service to wrap gmaps-for-apps geolocate in promise

@Matt-Jensen Wasn't this issue about _geocoding_ ([`GMaps.geocode`](https://hpneo.github.io/gmaps/examples/geolocation.html)) not _geolocation_ ([`Gmaps.geolocate`](https://hpneo.github.io/gmaps/examples/geocoding.html))?

**Comment by Matt-Jensen** [comment]
@zbeat That's correct, I've updated the issue name to avoid confusion.

**Comment by zbeat** [comment]
:+1: 

p.s. Nice work w/ all this!  We're looking at using it (instead of reinventing the wheel), when v0.4 is out.

**Comment by Matt-Jensen** [comment]
I really appreciate that @zbeat!

Contracting work has really pushed out delivery on 0.4, however my plan is to get it shipped over holidays.
