### ISSUE TITLE
_ember.default.String.singularize is not a function

### ISSUE THREAD

**Issue by OrKoN** [Matt-Jensen/ember-cli-g-maps#53]
Hi,

I am not sure if this module supports Ember 2.7.0 but it seems that Ember.String.singularize was removed in this version. 

I get an error `_ember.default.String.singularize is not a function` when I include g-maps.

**Comment by Matt-Jensen** [comment]
Thanks @OrKoN I'll look into it today.

**Comment by Matt-Jensen** [comment]
@OrKoN I'm not experiencing this with a fresh ember-cli@2.7.0/ember@2.7.0 app.  Can you share some code to reproduce?

**Comment by OrKoN** [comment]
@Matt-Jensen try the basic example `{{g-maps name="my-map" lat=lat lng=lng zoom=zoom}}` with `npm rm ember-data --save-dev`. 

Also in the docs http://emberjs.com/api/classes/Ember.String.html I don't find the singularize method.

**Comment by Matt-Jensen** [comment]
Ew, looks like ember-data extends `Ember.String` with the singularize method. Makes that an ember-cli-g-maps bug. I'm on it.
