### ISSUE TITLE
gMap service method for requesting map routes

### ISSUE THREAD

**Issue by Matt-Jensen** [Matt-Jensen/ember-cli-g-maps#6]
gMap service to wrap GMaps `travelRoute` method: https://hpneo.github.io/gmaps/documentation.html#GMaps-travelRoute
- [x] #5
- [ ] #32

Should support accepting:
A) two [lat,lng] coordinates
b) and/or two geocodes

**Comment by aansubarkah** [comment]
i'm waiting for this feature. many thanks for adding this on the next branch

**Comment by Matt-Jensen** [comment]
I'll try to expedite this, but if you find yourself with some time on your hands a PR would speed this along and be very appreciated (:

**Comment by Matt-Jensen** [comment]
nm
