### ISSUE TITLE
Error when pressing enter in Place Autocomplete field

### ISSUE THREAD

**Issue by bwbuchanan** [Matt-Jensen/ember-cli-g-maps#60]
How to reproduce:

1. Go to https://matt-jensen.github.io/ember-cli-g-maps/#/place-autocomplete/index
2. Type "NYC" into the autocomplete field
3. Press enter

Observe in console:

```
Uncaught TypeError: Cannot read property 'location' of undefined
    at r.<anonymous> (https://matt-jensen.github.io/ember-cli-g-maps/assets/vendor-8ace701c1f2eb849adbb40f30eb4afd8.js:19:1382)
...
```

The problem is in the `setup()` function in g-autocomplete.js:

```
  setup(input) {
    const autocomplete = new google.maps.places.Autocomplete(input);
    const handler = Ember.run.bind(this, function() {
      const place = autocomplete.getPlace();
      this.sendAction('on-select', {
        lat: place.geometry.location.lat(),
        lng: place.geometry.location.lng(),
        place
      });
    });
```

This function is assuming that `autocomplete.getPlace()` always returns a place that has a geometry. However, if the user doesn't select a place from the dropdown, the return value of `getPlace()` contains only the "name" key with the content of the `<input>` element.

I'm not 100% sure what is the right thing to do here.

One possibility is to not fire the on-select event unless a place has actually been chosen from the dropdown. Another would be to resubmit the content of the input field into the maps `AutocompleteService` and use the first matching result, which is probably what the user intended.

**Comment by Matt-Jensen** [comment]
Good find.  I think the later option should be given a go as long as we can find a way that doesn't add too much bloat. I'll see if I can get to this later tonight.

**Comment by Matt-Jensen** [comment]
I've opted for [Google's documented way](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete) of checking for a `place.geometry` property and issuing an error.  There may be better ways, but this approach avoids any thrown errors and allows responding to invalid selections.  Your thoughts?

**Comment by bwbuchanan** [comment]
Looks reasonable to me
