### ISSUE TITLE
Place autocomplete documentation indicates selection is MarkerPlace rather than PlaceResult

### ISSUE THREAD

**Issue by gheinze** [Matt-Jensen/ember-cli-g-maps#62]
The "Place Autocomplete" [demo](http://matt-jensen.github.io/ember-cli-g-maps/#/place-autocomplete/index) says:

> _place_ is a [MarkerPlace](https://developers.google.com/maps/documentation/javascript/3.exp/reference#MarkerPlace)

I believe this should be:

> _place_ is a [PlaceResult](https://developers.google.com/maps/documentation/javascript/reference#PlaceResult)

Source line may be [here](https://github.com/Matt-Jensen/ember-cli-g-maps/blob/master/tests/dummy/app/pods/place-autocomplete/index/template.hbs#L69)

**Comment by Matt-Jensen** [comment]
Correct. Thanks for pointing this out!
