### ISSUE TITLE
app.import fails when this addon is a dependency of another addon

### ISSUE THREAD

**Issue by 3tarazona** [Matt-Jensen/ember-cli-g-maps#69]
Hi, when this addon is a dependency of another addon, the consumer ember application will fail on initialization because the `app` object doesn't exists; throwing a message like this one 

`app.import is not a function`

This is a common problem. May I submit a PR to resole this issue?

**Comment by Matt-Jensen** [comment]
I don't see why not.  May I ask what the use case of your addon is?

**Comment by 3tarazona** [comment]
A collection applications developed using ember 2.5 which hasn't been migrated, and this addon is going to be used as another addon dependency.

**Comment by 3tarazona** [comment]
PR #70
