### ISSUE TITLE
More config options: streetViewControl, fullscreenControl

### ISSUE THREAD

**Issue by OakBehringer** [Matt-Jensen/ember-cli-g-maps#74]
Both are boolean options for maps, like zoomControl, scaleControl. Suggest:

showFullscreenControl
showStreetViewControl

Thanks!

**Comment by Matt-Jensen** [comment]
I agree, it's in the works on: [remove-gmaps branch](/Matt-Jensen/ember-cli-g-maps/tree/remove-gmaps)

**Comment by OakBehringer** [comment]
Thanks!
