### ISSUE TITLE
Can we remove Bower Dependency

### ISSUE THREAD

**Issue by devotox** [Matt-Jensen/ember-cli-g-maps#90]
The new state of Ember is to move all packages to npm and use things like ember-cli-node-assets to add the needed package to the addon rather than rely on the bower package be installed on the main application. 

Is this a possibility in this application. Also while doing this you can use fastboot-transform to wrap all of the g-maps code which would make sure it does not run in the fastboot sandbox

**Comment by Matt-Jensen** [comment]
#66 I'm counting on it.  If you have any feedback on the work done so far, lets track the discussion on that issue.
