### ISSUE TITLE
please adapt your code to last EmberJS releases

### ISSUE THREAD

**Issue by EmberJSParis** [Matt-Jensen/ember-cli-g-maps#93]
Here is correct today

    contentSecurityPolicy: {
  'default-src': "'none'",
  'script-src': "'self' 'unsafe-eval' *.googleapis.com maps.gstatic.com",
  'font-src': "'self' fonts.gstatic.com",
  'connect-src': "'self' maps.gstatic.com",
  'img-src': "'self' *.googleapis.com maps.gstatic.com csi.gstatic.com",
  'style-src': "'self' 'unsafe-inline' fonts.googleapis.com maps.gstatic.com"
},

**Comment by Matt-Jensen** [comment]
I'm not really seeing the difference between your content security policy configuration and the one documented here: http://matt-jensen.github.io/ember-cli-g-maps/#/setup/index

Could you please elaborate on what the difference is and what it's the issue you're seeking to address with the currently recommended configuration.

**Comment by EmberJSParis** [comment]
Hi Matt,

The code here as it is 

ENV.contentSecurityPolicy = {
  'default-src': "'none'",
  'script-src': "'self' 'unsafe-eval' *.googleapis.com maps.gstatic.com",
  'font-src': "'self' fonts.gstatic.com",
  'connect-src': "'self' maps.gstatic.com",
  'img-src': "'self' *.googleapis.com maps.gstatic.com csi.gstatic.com",
  'style-src': "'self' 'unsafe-inline' fonts.googleapis.com maps.gstatic.com"
};

produce error.

The correct code is

    contentSecurityPolicy: {
  'default-src': "'none'",
  'script-src': "'self' 'unsafe-eval' *.googleapis.com maps.gstatic.com",
  'font-src': "'self' fonts.gstatic.com",
  'connect-src': "'self' maps.gstatic.com",
  'img-src': "'self' *.googleapis.com maps.gstatic.com csi.gstatic.com",
  'style-src': "'self' 'unsafe-inline' fonts.googleapis.com maps.gstatic.com"
},

The ENV. should not be there

The issue is that web is full of small errors like that who poison the life of developers.

missing code everywhere like open <div id="mega-map »> but not close </div> etc https://github.com/binhums/ember-cli-mapbox

everywhere is time consuming

**Comment by EmberJSParis** [comment]
Matt, 

I have a bigger issue while I get lost in these small issues 

I have in a result route a loop like hereafter and I want to introduce longitude and latitude from this loop in the script hereafter

directly it doesn’t work so I thought to use the https://github.com/binhums/ember-cli-mapbox <https://github.com/binhums/ember-cli-mapbox>

but I am stuck in how to enter coordinates in your code

{{#mapbox-map mapId='ember-cli-mapbox.7c3914f2' as |map|}}
  {{#each positions as |position|}}
    {{mapbox-marker map=map coordinates=position.coordinates}}
  {{/each}}
{{/mapbox-map}}


Hereafter is my code;

I try to enter the  {{locdetail.loc_detail.longitude}} in the script

Can you help ? Should I use ember-cli-g-maps ?

How to solve position.coordinates for both longitude and latitude ?

Thanks


 {{#each model as |locdetail|}}
       <li> URL: <a href="{{locdetail.url}}">{{locdetail.url}}</a>
            <ul>IP: {{locdetail.ip}}</ul>
            <ul>Longitude: {{locdetail.loc_detail.longitude}} </ul>
            <ul>Latitude: {{locdetail.loc_detail.latitude}} </ul>
            <ul>City: {{locdetail.loc_detail.city}} </ul>
            <ul>Organisation: {{locdetail.loc_detail.org}} </ul>
            <ul>Region: {{locdetail.loc_detail.region}} </ul>
            <ul>Country: {{locdetail.loc_detail.country}} </ul>
            <ul>Country Name: {{locdetail.loc_detail.country_name}} </ul>
            <ul>Timezone: {{locdetail.loc_detail.timezone}} </ul>
       </li>

  {{/each}}


</ul>
 </div>
    </center>
</div>

</div>


<script data-template-name="post pop-up">
var text = 'Université Toulouse 1 Capitole, http://www.ut-capitole.fr/home-364807.kjsp © ARTADYS';

var lngt = 1.4367635999999493;
var Latt = 43.6067899;

var momentum = [lngt, Latt];

var popup = new mapboxgl.Popup({closeOnClick: false})
    .setLngLat(momentum)
    .setHTML(text)
    .addTo(map1);
   

</script>

**Comment by EmberJSParis** [comment]
Dear Matt,

I have not the link to Slack and is time consuming to correct all the small errors but I am more concerned by important issues like this one right now

Matt, 

I have a bigger issue while I get lost in these small issues 

I have in a result route a loop like hereafter and I want to introduce longitude and latitude from this loop in the script hereafter

directly it doesn’t work so I thought to use the https://github.com/binhums/ember-cli-mapbox

but I am stuck in how to enter coordinates in your code

{{#mapbox-map mapId='ember-cli-mapbox.7c3914f2' as |map|}} {{#each positions as |position|}} {{mapbox-marker map=map coordinates=position.coordinates}} {{/each}} {{/mapbox-map}}


Hereafter is my code;

I try to enter the {{locdetail.loc_detail.longitude}} in the script

Can you help ? Should I use ember-cli-g-maps ?

How to solve position.coordinates for both longitude and latitude ?

Thanks


 {{#each model as |locdetail|}}
       <li> URL: <a href="{{locdetail.url}}">{{locdetail.url}}</a>
            <ul>IP: {{locdetail.ip}}</ul>
            <ul>Longitude: {{locdetail.loc_detail.longitude}} </ul>
            <ul>Latitude: {{locdetail.loc_detail.latitude}} </ul>
            <ul>City: {{locdetail.loc_detail.city}} </ul>
            <ul>Organisation: {{locdetail.loc_detail.org}} </ul>
            <ul>Region: {{locdetail.loc_detail.region}} </ul>
            <ul>Country: {{locdetail.loc_detail.country}} </ul>
            <ul>Country Name: {{locdetail.loc_detail.country_name}} </ul>
            <ul>Timezone: {{locdetail.loc_detail.timezone}} </ul>
       </li>

  {{/each}}


</ul>
 </div>
    </center>
</div>

</div>


<script data-template-name="post pop-up">
var text = 'Université Toulouse 1 Capitole, http://www.ut-capitole.fr/home-364807.kjsp © ARTADYS';

var lngt = 1.4367635999999493;
var Latt = 43.6067899;

var momentum = [lngt, Latt];

var popup = new mapboxgl.Popup({closeOnClick: false})
    .setLngLat(momentum)
    .setHTML(text)
    .addTo(map1);
   

</script>



 


Cristian BEZA | Chief Action Officer ARTEDYS  | ARTADYS | 
Behavior, Personality, Attitudes, Loyalty, and Trend Tracking on the Internet | Strategy and Research
ARTADYS & Buzz Analytics | Paris & 
Washington, DC | www.artadys.com
+ 33 (0) 6 23 53 04 34 Cell  |
 
LinkedIn: http://www.linkedin.com/in/CristianBeza 
 
"A plan without action is not a plan. It's a speech."

Thomas Boone Pickens (Consultant billionaire )

**Comment by Matt-Jensen** [comment]
@EmberJSParis sorry I'm just not that familiar with ember-cli-mapbox and just wouldn't be of any help to you in this regard.  Why not ping  binhums? Or reach out to him on Slack?  Sure he'd love to help you with this.

**Comment by EmberJSParis** [comment]
Is OK Matt I thought you were at the origin of ember-cli-g-maps Thanks anyway


Cristian BEZA | Chief Action Officer ARTEDYS  | ARTADYS | 
Behavior, Personality, Attitudes, Loyalty, and Trend Tracking on the Internet | Strategy and Research
ARTADYS & Buzz Analytics | Paris & 
Washington, DC | www.artadys.com
+ 33 (0) 6 23 53 04 34 Cell  |
 
LinkedIn: http://www.linkedin.com/in/CristianBeza
 
"A plan without action is not a plan. It's a speech."

Thomas Boone Pickens (Consultant billionaire )
