### ISSUE TITLE
Advice on Travel Route

### ISSUE THREAD

**Issue by Peter-Barrett** [Matt-Jensen/ember-cli-g-maps#94]
Hey,

Could you point me in the right way regards using travel route or add route with ember-cli-g-maps? The example points to the Gmap version and I'm not too sure how to link them up.

Thanks,
Peter

**Comment by Matt-Jensen** [comment]
Travel Routes or Directions Services are not supported by the project. However it is possible to roll your own support by extending the `g-maps` component and then implementing Gmaps Travel Route.

Alternatively, if your feeling more adventurous, you could pull the /remove-gmaps branch and create a child component that implements: https://developers.google.com/maps/documentation/javascript/examples/directions-simple and consumes the `g-map` component like so:

```hbs
{{#g-map as |map|}}
   {{g-map-directions map}}
{{/g-map}}
```

I'd be happy to support you building that child component, should you decide to make it open source.

**Comment by Peter-Barrett** [comment]
Thanks for the quick response. I'll probably go with extending the component, thanks for the help!
