### ISSUE TITLE
How to get and update active markers?

### ISSUE THREAD

**Issue by sunik** [Matt-Jensen/ember-cli-g-maps#96]
I want to open the infoWindow for a marker on the map.

I tried getting the already set markers with `this.get('map.markers');` where `map` is my map service.
If I log this to the console i get `undefined`.

**Comment by Matt-Jensen** [comment]
I don't recommending using the map service.

See if you access the marker via g-map events otherwise if your requirements don't permit that try to render new markers on the map with:
```
markers: [
        {
          infoWindow: { content: '<p>They\'re Remarkable!</p>', visible: true }
        }
]
```

**Comment by sunik** [comment]
Alright. Will do.

**Comment by sunik** [comment]
I can't use events, so for the time beeing I will set all markers anew everytime I have to open a specific infoWindow.
